### ISSUE TITLE
IPFSBufferedFile doesn't have __content

### ISSUE THREAD

**Issue by davidgasquez** [AlgoveraAI/ipfspy#28]
Hey there! Seems there might be a bug on https://github.com/AlgoveraAI/ipfspy/blob/master/ipfspy/ipfsspec/bufferedfile.py#L42. The `self.__content` attribute doesn't exist.

**Comment by davidgasquez** [comment]
Any thoughts on this one? I'm happy to send a simple PR that adds a `self.__content=None` in the class initialization is that sounds good.

**Comment by moarshy** [comment]
apologies @davidgasquez. have added `self.__content=None`. 

https://github.com/AlgoveraAI/ipfspy/blob/master/ipfspy/ipfsspec/bufferedfile.py#L40

Could you please verify everything works?

**Comment by davidgasquez** [comment]
That fixed it! :dancers: 

Thanks @moarshy!
